name: base
channels:
  - pytorch-nightly
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aom=3.3.0=h27087fc_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - blas=1.0=mkl
  - blosc=1.21.1=h83bc5f7_3
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.1.1=h7a311fb_2
  - ca-certificates=2022.6.15=ha878542_0
  - certifi=2022.6.15=py39hf3d152e_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - cfitsio=4.1.0=hd9d235c_0
  - chardet=4.0.0=py39h06a4308_1003
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - conda=4.13.0=py39hf3d152e_1
  - conda-package-handling=1.8.1=py39hb9d737c_1
  - cryptography=37.0.2=py39hd97740a_0
  - cudatoolkit=11.7.0=hd8887f6_10
  - cudnn=8.4.1.50=hed8a83a_0
  - cytoolz=0.11.2=py39hb9d737c_2
  - dask-core=2022.6.0=pyhd8ed1ab_0
  - decorator=4.4.2=py_0
  - ffmpeg=4.3.2=h37c90e5_3
  - freetype=2.10.4=h0708190_1
  - fsspec=2022.5.0=pyhd8ed1ab_0
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39h78fa15d_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2022.2.22=py39hfcd4fa2_6
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h166bdaf_1
  - jxrlib=1.1=h7f98852_2
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libavif=0.10.1=h166bdaf_0
  - libblas=3.9.0=15_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=15_linux64_mkl
  - libcurl=7.83.1=h7bff187_0
  - libdeflate=1.12=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran4=7.5.0=h14aa051_19
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=15_linux64_mkl
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.20.1=h6239696_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hc85c160_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.12=h166bdaf_1
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=14.0.4=he0ac6c6_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - magma=2.5.4=h6103c52_2
  - mahotas=1.4.11=py39hde0f152_2
  - mkl=2022.1.0=h84fe81f_915
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.2.1=pyhd8ed1ab_0
  - nccl=2.12.12.1=h0800d71_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - ninja=1.11.0=h924138e_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1o=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycosat=0.6.3=py39hb9d737c_1010
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.13=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.0=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py39hb9d737c_1007
  - scipy=1.8.1=py39he49c0e8_0
  - sleef=3.5.1=h9b69904_2
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.38.5=h4ff8645_0
  - sympy=1.10.1=py39hf3d152e_0
  - tbb=2021.5.0=h924138e_1
  - tifffile=2022.5.4=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zfp=0.5.5=h9c3ff4c_8
  - zlib=1.2.12=h166bdaf_1
  - zlib-ng=2.0.6=h166bdaf_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - absl-py==0.15.0
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - airsim==1.7.0
    - alabaster==0.7.12
    - ale-py==0.7.4
    - antlr4-python3-runtime==4.9.3
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - ase==3.22.1
    - asttokens==2.0.5
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - atari-py==0.2.6
    - attrs==21.4.0
    - autopep8==1.6.0
    - autorom==0.4.2
    - babel==2.9.1
    - backcall==0.2.0
    - baselines==0.1.5
    - basicsr==1.3.4.8
    - beautifulsoup4==4.10.0
    - black==22.3.0
    - bleach==4.1.0
    - boltons==21.0.0
    - box2d-py==2.3.5
    - boxx==0.9.9
    - bpycv==0.2.43
    - cached-property==1.5.2
    - cachetools==4.2.4
    - casadi==3.5.5
    - catkin-pkg==0.5.2
    - cflib==0.1.20.1
    - clang==5.0
    - click==8.0.3
    - cma==3.2.2
    - colorama==0.4.4
    - colorlog==6.6.0
    - configparser==5.2.0
    - coverage==6.5.0
    - cycler==0.10.0
    - cython==0.29.26
    - debugpy==1.5.1
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - deprecation==2.1.0
    - dgl-cu113==0.9.0
    - dglgo==0.0.2
    - dill==0.3.4
    - diskcache==5.4.0
    - distro==1.7.0
    - dm-control==0.0.423341706
    - dm-env==1.5
    - dm-tree==0.1.7
    - dmc2gym==1.0.0
    - dnspython==2.2.1
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.17.1
    - elegantrl==0.3.3
    - empy==3.3.4
    - entrypoints==0.3
    - estorch==1.0.6
    - exceptiongroup==1.0.0
    - execnet==1.9.0
    - executing==0.8.2
    - facexlib==0.2.1.1
    - fastcore==1.5.27
    - fasteners==0.17.3
    - filelock==3.4.2
    - filterpy==1.4.5
    - fire==0.4.0
    - flatbuffers==1.12
    - fn==0.4.3
    - fonttools==4.28.3
    - fpdf==1.7.2
    - freetype-py==2.3.0
    - frozendict==2.3.0
    - frozenlist==1.3.0
    - future==0.18.2
    - future-fstrings==1.2.0
    - fvcore==0.1.5.post20211023
    - gast==0.4.0
    - gdown==4.2.0
    - geomdl==5.3.1
    - gitdb==4.0.9
    - gitpython==3.1.24
    - glfw==2.5.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googledrivedownloader==0.4
    - gprof2dot==2022.7.29
    - grpcio==1.50.0
    - grpcio-tools==1.50.0
    - gym==0.21.0
    - gym-minigrid==1.0.3
    - gym-notices==0.0.4
    - gym-pybullet-drones==0.0.3
    - h5py==3.1.0
    - hiredis==2.0.0
    - html5lib==1.1
    - hydra-core==1.1.1
    - imageio==2.13.3
    - imageio-ffmpeg==0.4.7
    - imagesize==1.4.1
    - imantics==0.1.12
    - imgviz==1.4.1
    - importlib-metadata==4.11.1
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - iopath==0.1.9
    - ipdb==0.13.9
    - ipykernel==6.7.0
    - ipython==8.0.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - isodate==0.6.1
    - isort==5.10.1
    - itk==5.2.1.post1
    - itk-core==5.2.1.post1
    - itk-filtering==5.2.1.post1
    - itk-io==5.2.1.post1
    - itk-numerics==5.2.1.post1
    - itk-registration==5.2.1.post1
    - itk-segmentation==5.2.1.post1
    - jax==0.3.13
    - jaxlib==0.3.10
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - jupyter-packaging==0.11.1
    - jupyter-server==1.13.4
    - jupyterlab==3.2.8
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - jupyterlab-widgets==1.0.2
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - labelme2coco==0.2.1
    - labmaze==1.0.5
    - libclang==12.0.0
    - libusb-package==1.0.26.0
    - lightning-bolts==0.5.0
    - littleutils==0.2.2
    - llvmlite==0.39.1
    - lmdb==1.2.1
    - lockfile==0.12.2
    - logdecorator==2.4
    - lovely-tensors==0.1.3
    - lxml==4.7.1
    - lz4==3.1.10
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib==3.2.2
    - matplotlib-inline==0.1.3
    - metaworld==0.1.0
    - metis==0.2a5
    - minexr==1.0.1
    - mistune==0.8.4
    - motion-planning-scenes==0.3.2
    - moviepy==1.0.3
    - mpi4py==3.1.3
    - msgpack==1.0.3
    - msgpack-numpy==0.4.8
    - msgpack-python==0.5.6
    - msgpack-rpc-python==0.4.1
    - mujoco-py==2.1.2.14
    - multi-agent-ale-py==0.1.11
    - multidict==6.0.2
    - multipledispatch==0.6.0
    - mypy-extensions==0.4.3
    - nashpy==0.0.21
    - nbclassic==0.3.5
    - nbclient==0.5.10
    - nbconvert==6.4.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - networkx==2.2
    - networkx-metis==1.0
    - nose==1.3.7
    - notebook==6.4.7
    - num2words==0.5.10
    - numba==0.56.3
    - numpy==1.23.4
    - numpy-stl==2.17.1
    - numpydoc==1.4.0
    - oauthlib==3.1.1
    - object2urdf==0.12
    - ogb==1.3.3
    - omegaconf==2.2.3
    - open-spiel==1.0.2
    - open3d==0.14.1
    - opencv-contrib-python==4.6.0.66
    - opencv-python==3.4.18.65
    - opt-einsum==3.3.0
    - outdated==0.2.1
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parameterized==0.8.1
    - parso==0.8.3
    - pastel==0.2.1
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pbr==5.11.0
    - petastorm==0.11.4
    - pettingzoo==1.13.1
    - pexpect==4.8.0
    - pickle5==0.0.11
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pip==22.1.2
    - platformdirs==2.5.2
    - pluggy==1.0.0
    - poethepoet==0.10.0
    - portalocker==2.3.2
    - prettytable==3.5.0
    - proglog==0.1.10
    - progressbar2==4.0.0
    - prometheus-client==0.12.0
    - promise==2.3
    - prompt-toolkit==3.0.24
    - protobuf==3.19.1
    - protobuf3-to-dict==0.1.5
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py4j==0.10.9
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.10.0
    - pybullet==3.2.5
    - pycocotools==2.0.3
    - pycodestyle==2.8.0
    - pycollada==0.6
    - pydantic==1.9.1
    - pydeprecate==0.3.1
    - pydot==1.4.2
    - pyecharts==1.9.1
    - pyglet==1.5.0
    - pygments==2.11.2
    - pymongo==4.3.2
    - pyopengl==3.1.0
    - pyparsing==2.4.7
    - pypng==0.0.21
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyquaternion==0.9.9
    - pyrender==0.1.45
    - pyrr==0.10.3
    - pyrsistent==0.18.1
    - pyspark==3.1.1
    - pytest==7.2.0
    - pytest-cov==4.0.0
    - pytest-mock==3.10.0
    - pytest-profiling==1.7.0
    - pytest-xdist==3.0.2
    - python-graphviz==0.20.1
    - python-louvain==0.16
    - python-snappy==0.6.1
    - python-utils==3.3.3
    - pytorch-lightning==1.6.0.dev0
    - pytz==2021.3
    - pyusb==1.2.1
    - pywavelets==1.2.0
    - pyyaml==5.1
    - pyzmq==22.3.0
    - qtpy==2.0.0
    - ray==1.8.0
    - rdflib==6.2.0
    - rdkit-pypi==2022.3.4
    - readerwriterlock==1.0.9
    - reagent==0.1.dev1407+gdd4438d
    - realesrgan==0.2.2.6
    - recsim-no-tf==0.2.3
    - redis==4.1.4
    - regex==2021.11.10
    - requests-oauthlib==1.3.0
    - rl-games==1.1.4
    - rospkg==1.4.0
    - rpclib==2.8.0rc0
    - rsa==4.8
    - rtree==0.9.7
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - sahi==0.8.22
    - scikit-image==0.19.0
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sentry-sdk==1.5.1
    - setproctitle==1.2.2
    - setuptools==65.5.0
    - shapely==1.8.0
    - shortuuid==1.0.8
    - shutup==0.2.0
    - simpleitk==2.1.1
    - simplejson==3.17.6
    - six==1.15.0
    - sklearn==0.0
    - smbus==1.1.post2
    - smmap==5.0.0
    - snakeviz==2.1.1
    - sniffio==1.2.0
    - snowballstemmer==2.2.0
    - soupsieve==2.3.1
    - sphinx==5.1.0
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-apidoc==0.3.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - split-folders==0.5.1
    - spyne==2.13.16
    - stable-baselines==2.10.2
    - stable-baselines3==1.6.0
    - stack-data==0.1.4
    - subprocess32==3.5.4
    - supersuit==3.3.1
    - tabulate==0.8.9
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.5
    - tensorflow==2.6.0
    - tensorflow-estimator==2.7.0
    - tensorflow-gpu==2.7.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - tensorflow-probability==0.14.1
    - tensorforce==0.6.5
    - termcolor==1.1.0
    - terminado==0.12.1
    - terminaltables==3.1.10
    - testpath==0.5.0
    - tf-slim==1.1.0
    - threadpoolctl==3.0.0
    - timm==0.4.12
    - tinydb==4.7.0
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.8.0
    - torch==1.12.0+cu113
    - torch-cluster==1.6.0
    - torch-geometric==2.1.0
    - torch-scatter==2.0.9
    - torch-sparse==0.6.15
    - torch-spline-conv==1.2.1
    - torchaudio==0.12.0+cu113
    - torchcde==0.2.5
    - torchdiffeq==0.2.3
    - torchdyn==1.0.1
    - torchmetrics==0.7.2
    - torchsde==0.2.5
    - torchvision==0.13.0+cu113
    - torchviz==0.0.2
    - tornado==6.2
    - tqdm==4.62.3
    - traitlets==5.1.1
    - trampoline==0.1.2
    - trimesh==3.9.42
    - typer==0.6.1
    - typing-extensions==4.4.0
    - urdfenvs==0.3.0
    - urdfpy==0.0.22
    - wandb==0.12.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - werkzeug==2.0.2
    - wget==3.2
    - wheel==0.37.0
    - widgetsnbextension==3.5.2
    - wrapt==1.12.1
    - xmljson==0.2.1
    - yacs==0.1.8
    - yapf==0.31.0
    - yarl==1.7.2
    - yaspin==2.1.0
    - zipp==3.6.0
    - zmq==0.0.0
prefix: /home/josyula/miniconda3
