wandb_version: 1

K_epochs:
  desc: null
  value: 80
_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668467169
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.9.13
      5: 0.12.9
      8:
      - 5
action_std:
  desc: null
  value: 0.6
action_std_decay_freq:
  desc: null
  value: 250000
action_std_decay_rate:
  desc: null
  value: 0.05
env_name:
  desc: null
  value: MultiRobotCarry
eps_clip:
  desc: null
  value: 0.2
gamma:
  desc: null
  value: 0.99
has_continuous_action_space:
  desc: null
  value: true
log_freq:
  desc: null
  value: 2000
lr_actor:
  desc: null
  value: 0.0003
lr_critic:
  desc: null
  value: 0.001
max_ep_len:
  desc: null
  value: 1000
max_training_timesteps:
  desc: null
  value: 3000000
min_action_std:
  desc: null
  value: 0.1
print_freq:
  desc: null
  value: 10000
random_seed:
  desc: null
  value: 42
save_model_freq:
  desc: null
  value: 100000
update_timestep:
  desc: null
  value: 2000
